name: Deploy Lambda

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-west-1
  LAMBDA_FUNCTION_NAME: contentService
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Lambda binary for provided.al2/provided.al2023
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/bootstrap .
          cd build && zip ../function.zip bootstrap && cd ..

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip